

CREATE TABLE EMPLOYEE(employName CHAR(10) ,
	employeeID CHAR(10) PRIMARY KEY NOT NULL,
	birthday CHAR(10),
	address CHAR(10),
	annualSalary INT,
	managerID CHAR(10),
	departmentID CHAR(10)
	);

CREATE TABLE DEPARTMENT(departName CHAR(10) ,
		departID CHAR(10) PRIMARY KEY NOT NULL,
		departManagerID CHAR(10)
		);

CREATE TABLE PROJECT(projName CHAR(10),
		projID CHAR(10) PRIMARY KEY NOT NULL,
		locateCity CHAR(10),
		manageDepartID CHAR(10)
		);


CREATE TABLE WORK(employeeID CHAR(10) NOT NULL,
		projID CHAR(10) NOT NULL,
		workTime char(20),
		PRIMARY KEY (employeeID,projID)
		);


CREATE TABLE RELATIVE(employeeID CHAR(10) PRIMARY KEY NOT NULL,
		name CHAR(10),
		gender CHAR(10)
		);


ALTER TABLE RELATIVE ADD CONSTRAINT consGender CHECK (gender IN('male','female'));

ALTER TABLE WORK ADD CONSTRAINT foreignProjID FOREIGN KEY(projID) REFERENCES PROJECT(projID)
ON DELETE CASCADE;

ALTER TABLE RELATIVE ADD CONSTRAINT foreignID FOREIGN KEY(employeeID) REFERENCES EMPLOYEE(employeeID)
ON DELETE CASCADE;


INSERT INTO EMPLOYEE VALUES ('kate','365','19901111','wall','1000','100','65');
INSERT INTO EMPLOYEE VALUES ('Tom','376','19901122','wall','2000','200','68');

INSERT INTO DEPARTMENT VALUES ('computer','65','100');
INSERT INTO DEPARTMENT VALUES ('math','68','200');

INSERT INTO PROJECT VALUES ('bike','10','newyork','100');
INSERT INTO PROJECT VALUES ('car','20','newyork','200');

INSERT INTO WORK VALUES ('365','10','7');
INSERT INTO WORK VALUES ('376','20','8');

INSERT INTO RELATIVE VALUES('365','John','male');
INSERT INTO RELATIVE VALUES('376','Anna','female');

CREATE TRIGGER updateSal
AFTER INSERT
ON WORK
REFERENCING NEW AS NW
FOR EACH ROW
UPDATE EMPLOYEE
SET annualSalary=annualSalary*1.02
WHERE employeeID = NW. employeeID;	


INSERT INTO WORK VALUES ('376','10','12');


