--连接查询
select Student.SNAME,Student.SNO from Student,Dept where Dept.DEPTNO = Student.DEPTNO AND Student.AGE <= 21 AND Student.SEX = 'f' AND Dept.DNAME = '信息';

--嵌套查询
--1
SELECT Student.SNAME FROM Student WHERE Student.SNO IN 
				( SELECT SC.SNO FROM SC,Course
				WHERE SC.CNO = Course.CNO GROUP BY SC.SNO HAVING SUM(Course.CREDIT) < 10);
--2
SELECT Student.SNAME,HIGH_LIST.CNO,HIGH_LIST.GRADE 
FROM Student NATURAL JOIN (SELECT SC.SNO,SC.CNO,SC.GRADE
			FROM SC NATURAL JOIN  (SELECT SC.CNO,MAX(SC.GRADE) AS GRADE FROM SC GROUP BY SC.CNO) AS HIGHEST ) AS HIGH_LIST
ORDER BY HIGH_LIST.CNO

--3
SELECT A.SNO FROM SC A NATURAL JOIN (
		SELECT B.CNO FROM SC B WHERE B.SNO = 1001) AS C
	    GROUP BY A.SNO HAVING COUNT(A.CNO) >= (SELECT COUNT(*) FROM (SELECT B.CNO FROM SC B WHERE B.SNO = 1001) AS D);

--4
SELECT Student.SNAME FROM Student WHERE Student.SNO IN (
				SELECT SC.SNO FROM SC NATURAL JOIN (
						SELECT Course.CNO FROM Course WHERE Course.TNO IN (
										SELECT TNO FROM Teacher WHERE TNAME = '张星')
											) AS ZX_COURSE
				GROUP BY SC.SNO HAVING COUNT(*) >= (
										SELECT COUNT(*) FROM Course WHERE Course.TNO IN (
															SELECT TNO FROM Teacher WHERE TNAME = '张星')
													)
					)


										
 
